version: '3.8'

services:
  golang-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - zincsearch

  zincsearch:
    image: zincsearch/zincsearch:latest
    ports:
      - "4080:4080"
    environment:
      - ZINCSEARCH_HTTP_PORT=4080
